# -*- coding: utf-8 -*-
"""5regular_graphs_order10_girth3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3w56u9-QEfFga7q-ECGbTdKPV_wbs4B
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
from scipy.linalg import eigvals

# Function to parse a graph from text
def parse_graph(lines):
    adjacency_matrix = np.zeros((10, 10), dtype=int)

    for line in lines:
        if ':' in line:
            vertex, neighbors = line.split(':')
            vertex = int(vertex.strip()) - 1  # Convert to 0-based index
            neighbors = list(map(lambda x: int(x) - 1, neighbors.split()))

            for neighbor in neighbors:
                adjacency_matrix[vertex, neighbor] = 1
                adjacency_matrix[neighbor, vertex] = 1  # ensure symmetry

    return adjacency_matrix


# Function to compute the second-largest eigenvalue
def second_largest_eigenvalue(matrix):
    eigenvalues = eigvals(matrix).real  # Get the real part of eigenvalues
    eigenvalues.sort()
    return eigenvalues[-2]  # Second-largest eigenvalue


# Main processing
filename = '5regular_order10_girth3.txt'

with open(filename, 'r') as file:
    lines = file.readlines()

results = []
current_graph_lines = []
graph_index = 1

for line in lines:
    line = line.strip()

    # Detect start of a new graph
    if line.startswith('Graph'):
        # Process the previously collected graph (if any)
        if current_graph_lines:
            adjacency_matrix = parse_graph(current_graph_lines)
            eigenvalue = second_largest_eigenvalue(adjacency_matrix)
            results.append((graph_index, adjacency_matrix, eigenvalue))
            graph_index += 1

        # Reset to collect adjacency lists for the next graph
        current_graph_lines = []

    elif line:  # Non-empty adjacency line
        current_graph_lines.append(line)

# Process the final graph
if current_graph_lines:
    adjacency_matrix = parse_graph(current_graph_lines)
    eigenvalue = second_largest_eigenvalue(adjacency_matrix)
    results.append((graph_index, adjacency_matrix, eigenvalue))


# Save results to file
output_file = 'graph_adjacency_second_eigenvalue.txt'

with open(output_file, 'w') as f:
    for graph_id, adjacency_matrix, eigenvalue in results:
        print(f"Graph {graph_id}: Second-largest eigenvalue = {eigenvalue}")
        print("Adjacency Matrix:")
        print(adjacency_matrix)
        print("\n")

        f.write(f"Graph {graph_id}: Second-largest eigenvalue = {eigenvalue}\n")
        f.write("Adjacency Matrix:\n")
        np.savetxt(f, adjacency_matrix, fmt='%d')
        f.write("\n\n")

print(f"Results saved to {output_file}")

files.download('graph_adjacency_second_eigenvalue.txt')