# -*- coding: utf-8 -*-
"""Degree sequence of Maverick graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1F2ouFpJoLmFBQuVMglY2XbSmdZuczL

Computing the degree sequences of the 4752 Maverick graphs
"""

from google.colab import files
uploaded = files.upload()

from collections import Counter
import string

# Define allowed vertex labels (0–9 + A–Z)
alphabet = list(string.digits + string.ascii_uppercase)

def parse_edges(graph_code):
    """Split the encoded string into edge pairs"""
    edges = [graph_code[i:i+2] for i in range(0, len(graph_code), 2)]
    return [(e[0], e[1]) for e in edges]

def degree_sequence(graph_code):
    """Return degree sequence sorted by vertex label"""
    edges = parse_edges(graph_code)
    degrees = Counter([v for edge in edges for v in edge])
    # Sort vertices by their label order (0–9, A–Z)
    return [degrees[v] for v in sorted(degrees.keys(), key=lambda x: alphabet.index(x))]

def is_regular(seq):
    """Check if all degrees are the same"""
    return len(set(seq)) == 1

# Read and process the uploaded file
degree_sequences = []
regular_graphs = []

with open("enum_maverick_graphs.txt") as f:
    for line in f:
        if line.strip():
            label, code = line.strip().split(maxsplit=1)
            seq = degree_sequence(code)
            degree_sequences.append((label, seq))
            if is_regular(seq):
                regular_graphs.append((label, seq))

# Print summary
print(f"Total graphs read: {len(degree_sequences)}")
print(f"Regular graphs found: {len(regular_graphs)}\n")

# Print first few examples
print("First 10 degree sequences:")
for label, seq in degree_sequences[:10]:
    print(f"{label}: {seq} {'(regular)' if is_regular(seq) else ''}")

# Save all sequences
with open("maverick_degrees.txt", "w") as out:
    for label, seq in degree_sequences:
        reg_tag = " (regular)" if is_regular(seq) else ""
        out.write(f"{label}: {seq}{reg_tag}\n")

# Save only regular graphs
with open("regular_mavericks.txt", "w") as out:
    for label, seq in regular_graphs:
        out.write(f"{label}: {seq}\n")

print("\nSaved all results to 'maverick_degrees.txt'")
print("Saved regular graphs to 'regular_mavericks.txt'")

from google.colab import files
files.download("maverick_degrees.txt")
files.download("regular_mavericks.txt")